name: car_price_env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - xgboost
  - catboost
  - matplotlib
  - seaborn
  - plotly
  - jupyter
  - tqdm
  - pip
  - pip:
      - python-dotenv
